language: ruby
rvm:
- 2.1.1
deploy:
  provider: heroku
  api_key:
    secure: q1CTORK1Wtk8B5mx1KdLEdkDp+LfeTgrEH+o1V9Z8N27pxEcyAfgq4QviqjXHof0H6ShKU9dGDTg98+TjGur/8fAMCuyXlrQS9S6pKT1UMac50Zm7iBwxamMCsbdQYvuHyNMPmyuoSxDfc+6Hs1ElN1WCnXYTW6DXodVT/RX16o=
  app: blooming-forest-4512
  on:
    repo: andrewdavidmackenzie/remoter
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake --trace db:migrate test
